server:
  port: 9050
  servlet.context-path: /account

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/Account-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

stripe:
  api:
    secret: sk_test_51TpWNYRhhlwhKoEWmlqL77bSnn59QifN2tza3FwwlfWyWMGeWpdDW4MgHWgJYlkDG3jKXb3egO79cjuuZtZabWdA00Q66BWbvU
  webhook:
    secret: whsec_0983abdbd7afec69f774ac59a9d06534515f0fa92f22397450898574e8297e14
